
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/binnny/Desktop/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("393x852")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 852,
    width = 393,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    393.0,
    45.0,
    fill="#64B3EC",
    outline="")

canvas.create_text(
    94.00000000000006,
    9.999999999999943,
    anchor="nw",
    text="Mind Memo - AI Diary",
    fill="#FFFFFF",
    font=("Milonga Regular", 20 * -1)
)

canvas.create_rectangle(
    37.00000000000006,
    109.99999999999994,
    356.00000000000006,
    164.99999999999994,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    37.00000000000006,
    188.99999999999994,
    356.00000000000006,
    442.99999999999994,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    37.00000000000006,
    464.99999999999994,
    356.00000000000006,
    632.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    48.00000000000006,
    112.99999999999994,
    anchor="nw",
    text="Title",
    fill="#000000",
    font=("Alata Regular", 14 * -1)
)

canvas.create_text(
    44.00000000000006,
    188.99999999999994,
    anchor="nw",
    text="Content",
    fill="#000000",
    font=("Alata Regular", 14 * -1)
)

canvas.create_text(
    43.00000000000006,
    464.99999999999994,
    anchor="nw",
    text="Outputs",
    fill="#000000",
    font=("Alata Regular", 14 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=122.00000000000006,
    y=654.0,
    width=149.0,
    height=44.0
)

canvas.create_text(
    145.00000000000006,
    64.99999999999994,
    anchor="nw",
    text="Write Diary",
    fill="#000000",
    font=("Alata Regular", 20 * -1)
)
window.resizable(False, False)
window.mainloop()
